name: Workflow for ae environment
description: This workflow runs for every deployment on non prod

inputs:
  application-name:
    description: "Name of the application"
    required: true
  environment:
    description: "target env to deploy to"
    required: true
  gcp-client-id:
    description: "gcp test client id"
    required: true
  gcp-subs-id:
    description: "gcp test subs id"
    required: true
  helm-path:
    description: "Path for the gcp helm file"
    required: false
    defult: ./deploy/helm

runs:
  using: "composite"
  steps:
   - name: Build and test
     uses: ./.github/actions/base-build
     with:
      gcp-client-id: ${{ inputs.gcp-client-id }}
      gcp-subs-id: ${{ inputs.gcp-subs-id }}
      env: ${{ inputs.environment }}
    
   - name: Generate image unique tag
     id: create-tag
     run: |
        echo "$GITHUB_RUN_NUMBER"
        echo "$GITHUB_SHA"
        short_sha=`echo $GITHUB_SHA | cut -c1-6` >> $GITHUB_OUTPUT
        echo "$short_sha"         
     shell: bash

   - name : Generate Image for the backend
     run: |
        echo "Name of appln: ${{ inputs.application-name }}"
        echo "Generated image tag: ${{ steps.create-tag.outputs.short_sha }}"
        echo "gcp-client-id: ${{ inputs.gcp-client-id }}"
        echo "gcp-subs-id: ${{ inputs.gcp-subs-id }}"
        echo "env: ${{ inputs.environment }}"
     shell: bash
      


