name: Repository Events
on: [push, pull_request, issues]
jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: commit id
              run: echo "$GITHUB_SHA"
            - name: branch name
              run: echo "$GITHUB_REF"
            - uses: actions/checkout@v4.1.1
