name: Expressions and contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and contexts by ${{ github.actor }},event: ${{ github.event_name}}"

jobs:
    using-expressions-windows:
        runs-on: windows-latest
        if: github.event_name == 'pull_request' || github.event_name == 'issues'              
        steps:
            - name: input Contextss
              run:  echo '${{  toJson(github) }}'
            - name: Run only for bug
              if: contains(github.event.issue.labels.*.name, 'bug')  
              run: echo '${{join(github.event.issue.labels.*.name,',')}}'

    using-expressions-contexts:
        runs-on: ubuntu-latest   
        if: github.event_name == 'push'     
        steps:
            - name: Expression
              id: expression
              run: |
               echo ${{ 1 }}
               echo ${{ true }}
               echo ${{ 'this is a string'}}
            - name: Dump Contexts
              run: |
                echo '${{  toJson(github) }}'                
                echo '${{  toJson(job) }}'
                echo '${{  toJson(steps) }}'
                echo '${{  toJson(runner) }}'
                echo '${{  toJson(secrets) }}'
            - name: runner details
              run: echo '${{  toJson(runner) }}'
            - name: input Contextss
              run:  echo '${{  toJson(github) }}'

