name: Manualtrigger
on:
    workflow_dispatch:
        inputs:
            string:
                description: 'string input'
                required: true
                default: 'Default value'
                type: string                
            number:
                description: 'number input'                
                default: 4
                type: number
            option:
                description: 'string input'
                required: true
                default: "info"
                type: choice
                options:
                        - info
                        - warning
                        - debug
            tags:
                description: 'Test scenario tags'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: environment
                required: true

jobs:
    workflow-dispatch-command:
        runs-on: ubuntu-latest
        steps:
            - name: current branch
              run: echo "$GITHUB_REF"
            - name: check-input-values
              run: |                 
                 echo "${{ inputs.string.default}}"
                 echo "${{ inputs.number.default}}"
                 echo "${{ inputs.option.default}}"
                 echo "${{ inputs.tags.description}}"
                 echo "${{ inputs.environment.description}}"

