name: Pipeline_main
on: 
    workflow_dispatch:
        inputs:            
            tags:
                description: 'Test scenario tags'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: environment
                default: ute
    push:
       branches:
            - 'main'  
            # When merging the feature branch to main branch
            # When pushing the code to main branch
            # Manual triggers 
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: echo Github_sha value
          run: echo "$GITHUB_SHA"
        - name: echo GITHUB_REF value
          run: echo "$GITHUB_REF" 
        - name: github workflow name
          run: echo '${{ github.workflow}}' 
        - name: github ref namess
          run: echo '${{ github.ref}}'
  