name: Pipeline_PullRequest
on: 
    workflow_dispatch:
        inputs:            
            environment:
                description: 'Environment to run tests against'
                type: environment
                default: dev
    push:
       branches:  # Trigger when push event triggered to any branch except main
            - '**'        
            - '!main'  
    pull_request: # Trigger when pull request from main branch
        branches:
            - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }} 
  cancel-in-progress: true
            
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"