name: Pipeline_main
on: 
    workflow_dispatch:
        inputs:            
            tags:
                description: 'Test scenario tags'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: environment
                default: ae
    push:
      branches:
            - 'main'  
            # When merging the feature branch to main branch
            # When pushing the code to main branch
            # Manual triggers     
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }} 
  cancel-in-progress: true

jobs:
  main:
    name: Build-push-deploy
    runs-on: ubuntu-latest
    environment: ae
    steps:
        - name: echo Github_sha value
          run: echo "$GITHUB_SHA"
        - name: echo GITHUB_REF value
          run: echo "$GITHUB_REF" 
        - name: github workflow name
          run: echo '${{ github.workflow}}' 
        - name: github ref namess
          run: echo '${{ github.ref}}'
        - name: github group name
          run: echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'

        - name: Checkout
          uses: actions/checkout@v4

        - name: Run workflow
          uses: ./.github/actions/non-prod-flow
          with:
            application-name: food-services
            environment: 'ae'
            gcp-client-id: ${{ vars.GCP_CLIENT_ID }}
            gcp-subs-id: ${{ vars.GCP_SUB_ID }}