name: statuscheck
on:
    push:
        branches:
            - main
jobs:
    job-1:        
        runs-on: ubuntu-latest
        steps:
          - name: step 1
            run: sleep 20
          - name: Fail the job
            id: Fail-1
            run: exit 1
          - name: step 2 failure
            if: failure() && steps.Fail-1.conclusion == 'failure' #In default, all steps are success
            run: echo 'Runs on Failure'
          - name: step 3 success
            if: success()
            run: echo 'Run for success'
          - name: step 4 always
            if: always()
            run: echo 'Run for always'
          - name: step 5 cancel
            if: cancelled()
            run: echo 'Run for cancel'
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo "Job 2"



