name: vars and secrets
on: [push]

jobs:
    vars-secret:
        runs-on: ${{ vars.JOBS_RUNNER }}
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
            - name: Run only if boolean secret is true;;
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "I ran"
            - name: Log varss
              run: |
               echo '${{ secrets.BOOLEAN_SECRET }}'
               echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
               echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
               echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"

