name: testing workflow commands
on: [push]

jobs:
  testing-workflow-commands:
    runs-on: ubuntu-latest
    steps:
      - name: display error message in runner machine
        run: echo"::error::missing semicolonss"  