name: RunWorkflow_RUN
on:
    workflow_run:
        workflows: [Repository Events] 
        types:
            - completed
jobs:
    run-the-workflow-based:
        runs-on: ubuntu-latest
        steps:
            - name: Execute the RunWorkflow_run
              run: |
               pwd
               ls -a
               ls

            