name: RunWorkflow_RUN
on:
    workflow_run:
        workflows: [Repository Events] 
        types:
            - completed # workflow will only run when Repository Events workflow completed
        branches: #Filter
            - main #workflow will only run when Repository events workflow completed in main branch
jobs:
    run-the-workflow-based:
        runs-on: ubuntu-latest
        steps:
            - name: Execute the RunWorkflow_run
              run: |
               pwd
               ls -a
               ls

            