name: testing workflow commands
on: [push]

jobs:
  testing-workflow-commands:
    runs-on: ubuntu-latest
    steps:
      - name: display error message in runner machine
        run: echo "::error::missing semicolon"  
      - name: Display error message with parameter
        run: echo "::error title=error title,file=app.js,
             line=2,endLine=3,column=5,endColumn=7::Missing semicolumn"
      - name: Display debug message with parameter
        run: echo "::debug title=debug title,file=app.js,
             line=2,endLine=3,column=5,endColumn=7::Missing semicolumn"
      - name: Display warning message with parameter
        run: echo "::warning title=warning title,file=app.js,
             line=2,endLine=3,column=5,endColumn=7::Missing semicolumn"
      - name: Display notice message with parameter
        run: echo "::notice title=notice title,file=app.js,
             line=2,endLine=3,column=5,endColumn=7::Missing semicolumn"
      - name: Group of logs
        run: |
             echo "::group::My Group title"
             echo "Inside group"
             echo "::end group::"
      - name: Masking a value
        run:  echo" ::add-mask::secret string"
      - name: Print the secret value after masking
        run:  echo "secret string"